[build]
  base    = "defesa-civil"
  publish = "dist"
  command = "npm install -g pnpm && pnpm install --no-frozen-lockfile && pnpm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
